name: aromind_app
description: "Aromind Mobile App â€“ Flutter UI for perfume recommendation"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ğŸ‘‰ Core dependencies
  http: ^1.2.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  image_picker: ^1.0.7
  image_picker_for_web: ^2.0.5
  intl: ^0.19.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/